[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm cache clean --force",
  "npm install --legacy-peer-deps",
  "echo 'Install phase completed successfully'"
]

[phases.build]
cmds = [
  "echo 'Starting build phase...'",
  "npm run build",
  "echo 'Frontend build completed'",
  "npx esbuild server/minimal.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/minimal.js",
  "echo 'Server build completed'",
  "ls -la dist/",
  "echo 'Build phase completed successfully'"
]

[start]
cmd = "node dist/minimal.js"

[variables]
NODE_ENV = "production"
PORT = "3000"
